import { motion } from "framer-motion";
import {
  Target,
  Sparkles,
  Activity,
  Trophy,
} from "lucide-react";

const steps = [
  {
    icon: Target,
    title: "Set Your Goal",
    description:
      "Choose whether you want to build muscle, lose fat, or improve fitness.",
  },
  {
    icon: Sparkles,
    title: "AI Creates Your Plan",
    description:
      "Receive personalized workouts and nutrition plans generated by AI.",
  },
  {
    icon: Activity,
    title: "Track Your Progress",
    description:
      "Log workouts, body measurements, and performance every day.",
  },
  {
    icon: Trophy,
    title: "Achieve Results",
    description:
      "Stay consistent and let BodyForge AI guide your transformation.",
  },
];

export default function HowItWorks() {
  return (
    <motion.section
  initial={{ opacity: 0, y: 30 }}
  whileInView={{ opacity: 1, y: 0 }}
  viewport={{ once: true }}
  transition={{ duration: 0.6 }} className="bg-slate-950 px-6 py-24">
      <div className="mx-auto max-w-7xl">

        <h2 className="mb-16 text-center text-4xl font-bold text-white">
          How It Works
        </h2>

        <div className="grid gap-8 md:grid-cols-4">

          {steps.map((step, index) => {
            const Icon = step.icon;

            return (
              <div
                key={index}
                className="rounded-2xl border border-slate-800 bg-slate-900 p-8 text-center transition-all duration-300 hover:-translate-y-2 hover:border-cyan-400 hover:shadow-xl hover:shadow-cyan-500/10"
              >
                <Icon className="mx-auto mb-6 h-12 w-12 text-cyan-400" />

                <h3 className="mb-3 text-2xl font-bold text-white">
                  {step.title}
                </h3>

                <p className="text-slate-400">
                  {step.description}
                </p>
              </div>
            );
          })}

        </div>

      </div>
    </motion.section>
  );
}